function getMonday(d) {
    d = new Date(d);
    var day = d.getDay(),
        diff = d.getDate() - day + (day == 0 ? -6 : 1); // adjust when day is sunday
    return new Date(d.setDate(diff));
}

const monday = getMonday(new Date());
const tuesday = new Date(getMonday(new Date()).setDate(monday.getDate() + 1));
const wednesday = new Date(getMonday(new Date()).setDate(monday.getDate() + 2));
const thursday = new Date(getMonday(new Date()).setDate(monday.getDate() + 3));
const friday = new Date(getMonday(new Date()).setDate(monday.getDate() + 4));
const saturday = new Date(getMonday(new Date()).setDate(monday.getDate() + 5));
const sunday = new Date(getMonday(new Date()).setDate(monday.getDate() + 6));

module.exports = () => {
    return {
        menu: [
            {
                date: monday,
                breakfast: {
                    Leite: "Leite de vaca integral",
                    "Composto vegetal": "Soja",
                    "Pão padrão / Ovolactovegetariano": "Pão careca",
                    "Pão vegetariano estrito": "Pão francês",
                    "Opção extra": "Cuzcuz",
                    Godura: "Manteiga / Creme vegetal",
                    "Complemento parão": "Queijo minas",
                    "Complemento vegetariano estrito": "Requeijão Vegano",
                    "Complemento ovolactovegetariano": "Queijo minas",
                    Fruta: "Banana",
                },
                lunch: {
                    "Salada 1": "Alface crespa com rúcula",
                    "Salada 2": "Tomate",
                    Molho: "Limão",
                    "Prato principal padrão": "Escalope ao molho de carne",
                    "Prato principal vegetariano estrito": "Bolinho de legumes vegano",
                    "Prato principal ovolactovegetariano": "Bolinho de legumes vegano",
                    Guarnição: "Purê de abóbora com leite de coco",
                    Acompanhamentos: "Arroz branco, arroz integral, feijão preto",
                    Sobremesa: "Doce paçoquinha",
                    Refresco: "Goiaba",
                },
                dinner: {
                    "Salada 1": "Alface americana com cenoura ralada",
                    "Salada 2": "Berinjela refogada",
                    Molho: " Oriental",
                    "Prato principal padrão": "Frango xadrez",
                    "Prato principal vegetariano estrito": "Grão de bico ao vinagrete",
                    "Prato principal ovolactovegetariano": "Grão de bico ao vinagrete",
                    Sopa: "Sopa Massinha com feijão preto",
                    Torrada: "Torrada",
                    Acompanhamentos: "Arroz branco, arroz integral, feijão preto",
                    Sobremesa: "Mamão",
                    Refresco: "Caju",
                },
            },
            {
                date: tuesday,

                breakfast: {
                    Leite: "Leite de vaca integral",
                    "Composto vegetal": "Soja",
                    "Pão padrão / Ovolactovegetariano": "Pão careca",
                    "Pão vegetariano estrito": "Pão francês",
                    "Opção extra": "Cuzcuz",
                    Godura: "Manteiga / Creme vegetal",
                    "Complemento parão": "Bebida láctea",
                    "Complemento vegetariano estrito": "Geléia de Frutas",
                    "Complemento ovolactovegetariano": "Bebida láctea",
                    Fruta: "Melão",
                },
                lunch: {
                    "Salada 1": " Mix de folhas",
                    "Salada 2": "Picles de pepino com cebola",
                    Molho: "Hortelã",
                    "Prato principal padrão": "Compa lombo suíno ao molho agridoce",
                    "Prato principal vegetariano estrito": "Bobó de palmito",
                    "Prato principal ovolactovegetariano": "Suflê de chuchu",
                    Guarnição: "Legumes salteados (cenoura, batata, abobrinha)",
                    Acompanhamentos: "Arroz branco, arroz integral, feijão preto",
                    Sobremesa: "Melancia",
                    Refresco: "Abacaxi",
                },
                dinner: {
                    "Salada 1": "Acelga com agrião",
                    "Salada 2": "Beterraba com salsinha e alho frito",
                    Molho: " Chimichurri",
                    "Prato principal padrão": "Escondidinho de carne de sol",
                    "Prato principal vegetariano estrito": "Soja xadrez",
                    "Prato principal ovolactovegetariano": "Soja xadrez",
                    Sopa: "Sopa de Tomate",
                    Torrada: "Torrada",
                    Acompanhamentos: "Arroz branco, arroz integral, feijão preto",
                    Sobremesa: "Maçã",
                    Refresco: "Morango",
                },
            },
            {
                date: wednesday,

                breakfast: {
                    Leite: "Leite de vaca integral",
                    "Composto vegetal": "Soja",
                    "Pão padrão / Ovolactovegetariano": "Pão careca",
                    "Pão vegetariano estrito": "Pão francês",
                    "Opção extra": "Cuzcuz",
                    Godura: "Manteiga / Creme vegetal",
                    "Complemento parão": "Ovos cozidos",
                    "Complemento vegetariano estrito": "Homus",
                    "Complemento ovolactovegetariano": "Ovos cozidos",
                    Fruta: "Abacaxi",
                },
                lunch: {
                    "Salada 1": "Alface lisa com chicória",
                    "Salada 2": "Salada de feijão fradinho",
                    Molho: "Àcido",
                    "Prato principal padrão": "Coxa e sobrecoxa á pizzaiolo",
                    "Prato principal vegetariano estrito": "Torta salgada de soja e legumes",
                    "Prato principal ovolactovegetariano": "Torta salgada de soja e legumes",
                    Guarnição: "Macarrão penne ao alho e óleo",
                    Acompanhamentos: "Arroz branco, arroz integral, feijão preto",
                    Sobremesa: "Salada de Frutas",
                    Refresco: "Acerola",
                },
                dinner: {
                    "Salada 1": " Salada de repolho",
                    "Salada 2": "Acelga",
                    Molho: " Limão",
                    "Prato principal padrão": "Isca de acebolada",
                    "Prato principal vegetariano estrito": "Estrogonofe de berinjela",
                    "Prato principal ovolactovegetariano": "Estrogonofe de berinjela",
                    Sopa: "Creme de espinafre",
                    Torrada: "Torrada",
                    Acompanhamentos: "Arroz branco, arroz integral, feijão preto",
                    Sobremesa: "Laranja",
                    Refresco: "Limão",
                },
            },
            {
                date: thursday,
                breakfast: {
                    Leite: "Leite de vaca integral",
                    "Composto vegetal": "Soja",
                    "Pão padrão / Ovolactovegetariano": "Pão careca",
                    "Pão vegetariano estrito": "Pão francês",
                    "Opção extra": "Cuzcuz",
                    Godura: "Manteiga / Creme vegetal",
                    "Complemento parão": "Carne moída",
                    "Complemento vegetariano estrito": "Guacamole",
                    "Complemento ovolactovegetariano": "Guacamole",
                    Fruta: "Mamão",
                },
                lunch: {
                    "Salada 1": "Alface crespa com manjericão",
                    "Salada 2": "Cenoura ralada",
                    Molho: "Mostarda e mel",
                    "Prato principal padrão": "Lombo suíno ao molho shoyo",
                    "Prato principal vegetariano estrito": "Moqueca de vegetais",
                    "Prato principal ovolactovegetariano": "Moqueca de vegetais",
                    Guarnição: "Batatas douradas",
                    Acompanhamentos: "Arroz branco, arroz integral, feijão preto",
                    Sobremesa: "Melão",
                    Refresco: "Tangerina",
                },
                dinner: {
                    "Salada 1": "Mix de folhas",
                    "Salada 2": "Tomate",
                    Molho: " Chimichurri",
                    "Prato principal padrão": "Filé de frango grelhado",
                    "Prato principal vegetariano estrito": "Almôndegas de grão de bico",
                    "Prato principal ovolactovegetariano": "Almôndegas de grão de bico",
                    Sopa: "Sopa vagem, agrião e macarrão",
                    Torrada: "Torrada",
                    Acompanhamentos: "Arroz branco, arroz integral, feijão preto",
                    Sobremesa: "Doce de banana caseiro",
                    Refresco: "Manga",
                },
            },
            {
                date: friday,
                breakfast: {
                    Leite: "Leite de vaca integral",
                    "Composto vegetal": "Soja",
                    "Pão padrão / Ovolactovegetariano": "Pão careca",
                    "Pão vegetariano estrito": "Pão francês",
                    "Opção extra": "Pão de queijo",
                    Godura: "Manteiga / Creme vegetal",
                    "Complemento parão": "Frango desfiado",
                    "Complemento vegetariano estrito": "Pasta de berinjela",
                    "Complemento ovolactovegetariano": "Ovos mexidos",
                    Fruta: "Melancia",
                },
                lunch: {
                    "Salada 1": "Couve Refogada",
                    "Salada 2": "Vinagrete",
                    Molho: "Molho de pimenta calabresa",
                    "Prato principal padrão": "Feijoada",
                    "Prato principal vegetariano estrito": "Feijoada vegetariana",
                    "Prato principal ovolactovegetariano": "Feijoada vegetariana",
                    Guarnição: "Farofa cebola",
                    Acompanhamentos: "Arroz branco, arroz integral, feijão preto",
                    Sobremesa: "Laranja",
                    Refresco: "Morango",
                },
                dinner: {
                    "Salada 1": "Repolho branco com rúcula",
                    "Salada 2": "Beterraba ralada com salsainha",
                    Molho: "Rosê",
                    "Prato principal padrão": "Silveirinha de carne",
                    "Prato principal vegetariano estrito": "Quibe de batatas com tofu",
                    "Prato principal ovolactovegetariano": "Abobrinha recheada com queijo",
                    Sopa: "Sopa Canjiquinha",
                    Torrada: "Torrada",
                    Acompanhamentos: "Arroz branco, arroz integral, feijão preto",
                    Sobremesa: "Banana",
                    Refresco: "Goiaba",
                },
            },
            {
                date: saturday,
                breakfast: {
                    Leite: "Leite de vaca integral",
                    "Composto vegetal": "Soja",
                    "Pão padrão / Ovolactovegetariano": "Pão careca",
                    "Pão vegetariano estrito": "Pão francês",
                    "Opção extra": "Pão de queijo",
                    Godura: "Manteiga / Creme vegetal",
                    "Complemento parão": "Queijo muçarela",
                    "Complemento vegetariano estrito": "Pasta de brócolis com espinafre",
                    "Complemento ovolactovegetariano": "Queijo muçarela",
                    Fruta: "Tangerina",
                },
                lunch: {
                    "Salada 1": "Alface lisa e roxa",
                    "Salada 2": "Tabule",
                    Molho: "Manjericão",
                    "Prato principal padrão": "Coxa e sobrecoxa ao forno com manteiga de ervas",
                    "Prato principal vegetariano estrito":
                        "Cozido de proteína de soja com vegetais",
                    "Prato principal ovolactovegetariano":
                        "Omelete com jardineira de legumes (cenoura, milho verde, pimentões coloridos, cheiro verde)",
                    Guarnição: "Beterraba ao forno",
                    Acompanhamentos: "Arroz branco, arroz integral, feijão preto",
                    Sobremesa: "Mamão",
                    Refresco: "Uva",
                },
                dinner: {
                    "Salada 1": "Alface crespa",
                    "Salada 2": "Chuchu com milho verde",
                    Molho: "Hortelã",
                    "Prato principal padrão": "Peixe á escabeche",
                    "Prato principal vegetariano estrito": "Curry de soja",
                    "Prato principal ovolactovegetariano": "Curry de soja",
                    Sopa: "Sopa Caldo de legumes",
                    Torrada: "Torrada",
                    Acompanhamentos: "Arroz branco, arroz integral, feijão preto",
                    Sobremesa: "Melão",
                    Refresco: "Abacaxi",
                },
            },
            {
                date: sunday,
                breakfast: {
                    Leite: "Leite de vaca integral",
                    "Composto vegetal": "Soja",
                    "Pão padrão / Ovolactovegetariano": "Pão careca",
                    "Pão vegetariano estrito": "Pão francês",
                    "Opção extra": "Pão de queijo",
                    Godura: "Manteiga / Creme vegetal",
                    "Complemento parão": "Presunto",
                    "Complemento vegetariano estrito": "Pasta de tomate",
                    "Complemento ovolactovegetariano": "Pasta de tomate",
                    Fruta: "Banana",
                },
                lunch: {
                    "Salada 1": "Repolho branco com rúcula",
                    "Salada 2": "Salada de abobrinha",
                    Molho: "Molho gengibre",
                    "Prato principal padrão": "Lasanha à bolonhesa",
                    "Prato principal vegetariano estrito": "Charuto de couve e lentilha",
                    "Prato principal ovolactovegetariano": "Charuto de couve e lentilha",
                    Guarnição: "Jardineira verde ( chuchu, vagem, brócolis e ervilha)",
                    Acompanhamentos: "Arroz branco, arroz integral, feijão preto",
                    Sobremesa: "Abacaxi",
                    Refresco: "Limão",
                },
                dinner: {
                    "Salada 1": " Alface, rabanete e manjericão",
                    "Salada 2": "Cenoura ralada",
                    Molho: "Molho de mostarda e mel",
                    "Prato principal padrão": "Almôndegas ao sugo",
                    "Prato principal vegetariano estrito": "Tomate recheado com homus e ervas",
                    "Prato principal ovolactovegetariano":
                        "Moussaka (berinjela grelhada, batata cozida, molho de tomate, molho branco, queijo)",
                    Sopa: "Sopa creme de cebola",
                    Torrada: "Torrada",
                    Acompanhamentos: "Arroz branco, arroz integral, feijão preto",
                    Sobremesa: "Laranja",
                    Refresco: "Acerola",
                },
            },
        ],
    };
};
